/**
 * School Dashboard JavaScript
 * Page-specific functionality for school.html
 * 
 * This file contains all school-dashboard specific functions.
 * It depends on main.js being loaded first for shared utilities.
 */

// Current stream ID for live streaming
let currentStreamId = null;

/**
 * Initialize school dashboard when DOM is ready
 */
document.addEventListener('DOMContentLoaded', () => {
    // Check authentication first
    checkAuth();
    
    // Initialize mobile menu
    initMobileMenu();
    
    // Load initial dashboard data
    loadDashboardStats();
    
    // Set up auto-refresh for live data (every 30 seconds)
    setInterval(() => {
        loadDashboardStats();
    }, 30000);
});

/**
 * Show a specific section
 * @param {string} sectionId - The ID of the section to show
 */
function showSection(sectionId) {
    // Hide all sections
    document.querySelectorAll('.section').forEach(s => s.classList.remove('active'));
    
    // Show selected section
    const section = document.getElementById(sectionId);
    if (section) {
        section.classList.add('active');
    }
    
    // Load data for specific sections
    if (sectionId === 'statistics') {
        loadPlayerStats();
    } else if (sectionId === 'ml-training') {
        loadTrainingJobs();
    } else if (sectionId === 'live-match') {
        loadStreams();
    } else if (sectionId === 'matches') {
        loadMatches();
    }
}

// Export showSection to window for onclick handlers
window.showSection = showSection;

/**
 * Load dashboard statistics
 */
async function loadDashboardStats() {
    try {
        // Load total players count
        const playersResponse = await fetch(`${API_BASE}/players`, {
            headers: getAuthHeaders()
        });
        if (playersResponse.ok) {
            const playersData = await playersResponse.json();
            updateElement('totalPlayers', playersData.players?.length || 0);
        }
        
        // Load live streams count
        const streamsResponse = await fetch(`${API_BASE}/live-stream/list`, {
            headers: getAuthHeaders()
        });
        if (streamsResponse.ok) {
            const streamsData = await streamsResponse.json();
            const activeStreams = streamsData.streams?.filter(s => s.status === 'active').length || 0;
            updateElement('liveMatches', activeStreams);
        }
        
        // Load top players for "Top Talent" count
        const topPlayersResponse = await fetch(`${API_BASE}/ai/top-players?limit=100`, {
            headers: getAuthHeaders()
        });
        if (topPlayersResponse.ok) {
            const topData = await topPlayersResponse.json();
            updateElement('topTalent', topData.top_players?.length || 0);
        }
    } catch (error) {
        console.error('Error loading dashboard stats:', error);
    }
}

/**
 * Helper to safely update element text
 */
function updateElement(id, value) {
    const element = document.getElementById(id);
    if (element) {
        element.textContent = value;
    }
}

// =============================================
// Player Management Functions
// =============================================

/**
 * Save a new player
 * @param {Event} e - Form submit event
 */
async function savePlayer(e) {
    e.preventDefault();
    
    // Get team_id from current user with validation
    let teamId = currentUser?.entity_id;
    
    // Validate team_id - must be a positive integer
    if (!teamId || typeof teamId !== 'number' || teamId <= 0 || !Number.isInteger(teamId)) {
        console.warn('Invalid team_id, prompting user or using session default');
        // Use a session-based default or prompt - for now use null to let API handle it
        teamId = null;
    }
    
    // Parse height to integer (remove 'cm' suffix if present)
    let heightValue = document.getElementById('playerHeight').value;
    let heightCm = null;
    if (heightValue) {
        heightCm = parseInt(heightValue.replace(/[^0-9]/g, '')) || null;
    }
    
    // Note: district, sector, cell, village fields exist in the form but aren't stored 
    // in the database - they're sent for future use but won't be persisted currently
    const district = document.getElementById('playerDistrict').value || null;
    const sector = document.getElementById('playerSector').value || null;
    const cell = document.getElementById('playerCell').value || null;
    const village = document.getElementById('playerVillage').value || null;
    
    // Note: Registration number is auto-generated by the backend, not user-provided
    // The regNumber field in the form is ignored by the backend
    
    const data = {
        name: document.getElementById('playerName').value,
        dob: document.getElementById('playerDob').value,
        nationality: document.getElementById('playerNationality').value,
        position: document.getElementById('playerPosition').value,
        // Map team_id to school_id for school users
        school_id: teamId,
        // Height from form (parsed to integer)
        height_cm: heightCm,
        jersey_number: null
    };
    
    // Log the data being sent for debugging
    console.log('Sending player data to API:', data);

    try {
        const response = await fetch(`${API_BASE}/players`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify(data)
        });
        
        if (response.ok) {
            const data = await response.json();
            showToast(`Player added successfully! Registration: ${data.registration_number || 'N/A'}`, 'success');
            document.getElementById('playerForm').reset();
            loadDashboardStats(); // Refresh stats
        } else {
            const errorData = await response.json();
            showToast(errorData.error || 'Error adding player', 'error');
        }
    } catch (error) {
        console.error('Error:', error);
        showToast('Error adding player', 'error');
    }
}

// Export to window for onclick handlers
window.savePlayer = savePlayer;

// =============================================
// Live Stream Functions
// =============================================

/**
 * Create a new live stream
 */
async function createStream() {
    const teamId = currentUser?.entity_id || 1;
    const matchId = 1; // Could be dynamic based on selection
    
    try {
        const response = await fetch(`${API_BASE}/live-stream/create`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({
                match_id: matchId,
                team_id: teamId,
                stream_name: 'School Match Stream'
            })
        });
        
        const data = await response.json();
        
        if (data.success) {
            document.getElementById('streamInfo').style.display = 'block';
            document.getElementById('rtmpUrl').value = data.rtmp_url;
            document.getElementById('watchUrl').value = data.stream_url;
            document.getElementById('streamKey').value = data.stream_key;
            currentStreamId = data.stream_id;
            showToast('Stream created!', 'success');
        } else {
            showToast(data.error || 'Error creating stream', 'error');
        }
    } catch (error) {
        console.error('Error:', error);
        showToast('Error creating stream', 'error');
    }
}

/**
 * Start the current stream
 */
async function startStream() {
    if (!currentStreamId) {
        showToast('No stream to start', 'warning');
        return;
    }
    
    try {
        const response = await fetch(`${API_BASE}/live-stream/start/${currentStreamId}`, {
            method: 'POST',
            headers: getAuthHeaders()
        });
        
        const data = await response.json();
        if (data.success) {
            showToast('Stream started!', 'success');
        } else {
            showToast(data.error || 'Error starting stream', 'error');
        }
    } catch (error) {
        showToast('Error starting stream', 'error');
    }
}

/**
 * Stop the current stream
 */
async function stopStream() {
    if (!currentStreamId) {
        showToast('No stream to stop', 'warning');
        return;
    }
    
    try {
        const response = await fetch(`${API_BASE}/live-stream/stop/${currentStreamId}`, {
            method: 'POST',
            headers: getAuthHeaders()
        });
        
        const data = await response.json();
        if (data.success) {
            showToast('Stream stopped!', 'success');
        } else {
            showToast(data.error || 'Error stopping stream', 'error');
        }
    } catch (error) {
        showToast('Error stopping stream', 'error');
    }
}

/**
 * Load and display all streams
 */
async function loadStreams() {
    const container = document.getElementById('streamsList');
    if (!container) return;
    
    try {
        const response = await fetch(`${API_BASE}/live-stream/list`, {
            headers: getAuthHeaders()
        });
        const data = await response.json();
        
        if (!data.streams || data.streams.length === 0) {
            container.innerHTML = `
                <div class="streams-empty">
                    <i class="fas fa-video-slash"></i>
                    <p>No active streams. Click "Start New Stream" to begin.</p>
                </div>
            `;
            return;
        }
        
        container.innerHTML = data.streams.map(stream => `
            <div class="stream-list-item">
                <div class="stream-info-left">
                    <div class="stream-status-indicator ${stream.status}"></div>
                    <div class="stream-details">
                        <h4>${stream.stream_name || 'Unnamed Stream'}</h4>
                        <p>${stream.status === 'active' ? '🔴 Live' : '⚪ Inactive'} | Created: ${stream.created_at ? new Date(stream.created_at).toLocaleDateString() : 'N/A'}</p>
                    </div>
                </div>
                <div class="stream-actions">
                    ${stream.status !== 'active' 
                        ? `<button class="btn-success" onclick="selectStream(${stream.id})">
                                <i class="fas fa-play"></i> Start
                           </button>`
                        : `<button class="btn-danger" onclick="selectAndStopStream(${stream.id})">
                                <i class="fas fa-stop"></i> Stop
                           </button>`
                    }
                </div>
            </div>
        `).join('');
        
    } catch (error) {
        console.error('Error:', error);
        container.innerHTML = `
            <div class="streams-empty">
                <i class="fas fa-exclamation-triangle"></i>
                <p>Error loading streams. Please try again.</p>
            </div>
        `;
    }
}

/**
 * Select a stream to manage
 */
function selectStream(streamId) {
    currentStreamId = streamId;
    // Show stream info for selected stream
    const streamInfo = document.getElementById('streamInfo');
    if (streamInfo) {
        streamInfo.style.display = 'block';
        document.getElementById('rtmpUrl').value = 'Select stream to see RTMP URL';
        document.getElementById('watchUrl').value = 'Select stream to see Watch URL';
        document.getElementById('streamKey').value = 'Select stream to see Key';
    }
    showToast('Stream selected', 'success');
}

/**
 * Select and stop a stream
 */
async function selectAndStopStream(streamId) {
    currentStreamId = streamId;
    await stopStream();
    loadStreams();
}

// Export additional stream functions
window.selectStream = selectStream;
window.selectAndStopStream = selectAndStopStream;

// Export stream functions to window
window.createStream = createStream;
window.startStream = startStream;
window.stopStream = stopStream;
window.loadStreams = loadStreams;

// =============================================
// ML Training Functions
// =============================================

/**
 * Create a new ML training job
 */
async function createTraining() {
    try {
        const response = await fetch(`${API_BASE}/live-stream/training/create`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({
                name: 'Player Detection Model',
                description: 'Train YOLO for player detection',
                model_type: 'yolov8'
            })
        });
        
        const data = await response.json();
        if (data.success) {
            showToast('Training job created!', 'success');
            loadTrainingJobs(); // Refresh the list
        } else {
            showToast(data.error || 'Error creating training job', 'error');
        }
    } catch (error) {
        console.error('Error:', error);
        showToast('Error creating training job', 'error');
    }
}

/**
 * Load and display all training jobs
 */
async function loadTrainingJobs() {
    const container = document.getElementById('trainingJobs');
    if (!container) return;
    
    try {
        const response = await fetch(`${API_BASE}/live-stream/training/list`, {
            headers: getAuthHeaders()
        });
        const data = await response.json();
        
        if (!data.trainings || data.trainings.length === 0) {
            container.innerHTML = `
                <div class="training-empty">
                    <i class="fas fa-brain"></i>
                    <p>No training jobs. Click "New Training Job" to start.</p>
                </div>
            `;
            return;
        }
        
        container.innerHTML = data.trainings.map(job => `
            <div class="training-card ${job.status}">
                <div class="training-header">
                    <h4>${job.name}</h4>
                    <span class="training-status status-${job.status}">${job.status}</span>
                </div>
                <div class="training-details">
                    <p><strong>Model:</strong> ${job.model_type}</p>
                    <p><strong>Progress:</strong> ${job.progress || 0}%</p>
                    ${job.description ? `<p>${job.description}</p>` : ''}
                </div>
            </div>
        `).join('');
        
    } catch (error) {
        console.error('Error:', error);
        container.innerHTML = `
            <div class="training-empty">
                <i class="fas fa-exclamation-triangle"></i>
                <p>Error loading training jobs. Please try again.</p>
            </div>
        `;
    }
}

// Export training functions to window
window.createTraining = createTraining;
window.loadTrainingJobs = loadTrainingJobs;

// =============================================
// Match Management Functions
// =============================================

/**
 * Load and display all matches
 */
async function loadMatches() {
    const container = document.getElementById('matchesTableBody');
    if (!container) return;
    
    try {
        const response = await fetch(`${API_BASE}/matches`, {
            headers: getAuthHeaders()
        });
        const data = await response.json();
        
        if (!data.matches || data.matches.length === 0) {
            container.innerHTML = '<tr><td colspan="6" class="empty-state">No matches found</td></tr>';
            return;
        }
        
        container.innerHTML = data.matches.map(match => `
            <tr>
                <td>${match.match_date ? new Date(match.match_date).toLocaleDateString() : 'TBD'}</td>
                <td>${escapeHtml(match.opponent || 'TBD')}</td>
                <td>${escapeHtml(match.venue || 'TBD')}</td>
                <td>${match.home_score !== null ? match.home_score : '-'} - ${match.away_score !== null ? match.away_score : '-'}</td>
                <td><span class="status-badge status-${match.status || 'scheduled'}">${match.status || 'scheduled'}</span></td>
                <td>
                    <button class="btn btn-sm btn-secondary" onclick="editMatch(${match.id})">
                        <i class="fas fa-edit"></i>
                    </button>
                    <button class="btn btn-sm btn-danger" onclick="deleteMatch(${match.id})">
                        <i class="fas fa-trash"></i>
                    </button>
                </td>
            </tr>
        `).join('');
        
    } catch (error) {
        console.error('Error:', error);
        container.innerHTML = '<tr><td colspan="6" class="error">Error loading matches</td></tr>';
    }
}

/**
 * Show the add match modal
 */
function showAddMatchModal() {
    document.getElementById('matchModalTitle').textContent = 'Add New Match';
    document.getElementById('matchForm').reset();
    document.getElementById('matchId').value = '';
    document.getElementById('matchModal').classList.add('active');
}

/**
 * Close the match modal
 */
function closeMatchModal() {
    document.getElementById('matchModal').classList.remove('active');
}

/**
 * Edit an existing match
 */
async function editMatch(matchId) {
    try {
        const response = await fetch(`${API_BASE}/matches/${matchId}`, {
            headers: getAuthHeaders()
        });
        const data = await response.json();
        
        if (data.match) {
            const match = data.match;
            document.getElementById('matchModalTitle').textContent = 'Edit Match';
            document.getElementById('matchId').value = match.id;
            document.getElementById('matchDate').value = match.match_date ? match.match_date.slice(0, 16) : '';
            document.getElementById('matchOpponent').value = match.opponent || '';
            document.getElementById('matchVenue').value = match.venue || '';
            document.getElementById('matchStatus').value = match.status || 'scheduled';
            document.getElementById('homeScore').value = match.home_score !== null ? match.home_score : '';
            document.getElementById('awayScore').value = match.away_score !== null ? match.away_score : '';
            document.getElementById('matchNotes').value = match.notes || '';
            document.getElementById('matchModal').classList.add('active');
        }
    } catch (error) {
        console.error('Error:', error);
        showToast('Error loading match details', 'error');
    }
}

/**
 * Save a match (create or update)
 */
async function saveMatch(e) {
    e.preventDefault();
    
    const matchId = document.getElementById('matchId').value;
    const data = {
        match_date: document.getElementById('matchDate').value,
        opponent: document.getElementById('matchOpponent').value,
        venue: document.getElementById('matchVenue').value,
        status: document.getElementById('matchStatus').value,
        home_score: document.getElementById('homeScore').value ? parseInt(document.getElementById('homeScore').value) : null,
        away_score: document.getElementById('awayScore').value ? parseInt(document.getElementById('awayScore').value) : null,
        notes: document.getElementById('matchNotes').value || null
    };
    
    try {
        const url = matchId ? `${API_BASE}/matches/${matchId}` : `${API_BASE}/matches`;
        const method = matchId ? 'PUT' : 'POST';
        
        const response = await fetch(url, {
            method: method,
            headers: getAuthHeaders(),
            body: JSON.stringify(data)
        });
        
        const result = await response.json();
        
        if (response.ok) {
            showToast(matchId ? 'Match updated successfully!' : 'Match added successfully!', 'success');
            closeMatchModal();
            loadMatches();
        } else {
            showToast(result.error || 'Error saving match', 'error');
        }
    } catch (error) {
        console.error('Error:', error);
        showToast('Error saving match', 'error');
    }
}

/**
 * Delete a match
 */
async function deleteMatch(matchId) {
    if (!confirm('Are you sure you want to delete this match?')) {
        return;
    }
    
    try {
        const response = await fetch(`${API_BASE}/matches/${matchId}`, {
            method: 'DELETE',
            headers: getAuthHeaders()
        });
        
        if (response.ok) {
            showToast('Match deleted successfully!', 'success');
            loadMatches();
        } else {
            const data = await response.json();
            showToast(data.error || 'Error deleting match', 'error');
        }
    } catch (error) {
        console.error('Error:', error);
        showToast('Error deleting match', 'error');
    }
}

/**
 * Search/filter matches
 */
function searchMatches() {
    const searchTerm = document.getElementById('matchSearch')?.value?.toLowerCase() || '';
    const statusFilter = document.getElementById('filterMatchStatus')?.value || '';
    
    const rows = document.querySelectorAll('#matchesTableBody tr');
    rows.forEach(row => {
        const text = row.textContent.toLowerCase();
        const status = row.querySelector('.status-badge')?.textContent?.toLowerCase() || '';
        
        const matchesSearch = text.includes(searchTerm);
        const matchesStatus = !statusFilter || status.includes(statusFilter);
        
        row.style.display = matchesSearch && matchesStatus ? '' : 'none';
    });
}

// Export match functions to window
window.loadMatches = loadMatches;
window.showAddMatchModal = showAddMatchModal;
window.closeMatchModal = closeMatchModal;
window.editMatch = editMatch;
window.saveMatch = saveMatch;
window.deleteMatch = deleteMatch;
window.searchMatches = searchMatches;

// =============================================
// Statistics Functions
// =============================================

/**
 * Load and display player statistics
 */
async function loadPlayerStats() {
    const container = document.getElementById('playerStats');
    if (!container) return;
    
    try {
        const response = await fetch(`${API_BASE}/ai/top-players?limit=10`, {
            headers: getAuthHeaders()
        });
        const data = await response.json();
        
        if (!data.top_players || data.top_players.length === 0) {
            container.innerHTML = '<p class="empty-state">No player statistics available</p>';
            return;
        }
        
        container.innerHTML = data.top_players.map((player, index) => `
            <div class="player-stat-card">
                <div class="rank">#${index + 1}</div>
                <div class="player-info">
                    <h4>${player.name || 'Unknown Player'}</h4>
                    <p>${player.position || 'N/A'} | ${player.match_count || 0} matches</p>
                </div>
                <div class="player-metrics">
                    <div class="metric">
                        <span class="metric-value">${(player.avg_performance || 0).toFixed(1)}</span>
                        <span class="metric-label">Score</span>
                    </div>
                    <div class="metric">
                        <span class="metric-value">${(player.avg_distance || 0).toFixed(0)}m</span>
                        <span class="metric-label">Avg Distance</span>
                    </div>
                    <div class="metric">
                        <span class="metric-value">${(player.avg_speed || 0).toFixed(1)} m/s</span>
                        <span class="metric-label">Avg Speed</span>
                    </div>
                </div>
            </div>
        `).join('');
        
    } catch (error) {
        console.error('Error:', error);
        container.innerHTML = '<p class="error">Error loading player statistics</p>';
    }
}

// Export stats function to window
window.loadPlayerStats = loadPlayerStats;
